### ISSUE TITLE
Parse error: syntax error, unexpected ')', expecting variable (T_VARIABLE)

### ISSUE THREAD

**Issue by maofree** [PrestaShopCorp/ps_eventbus#183]
Hi
I report this bug after the upgrade to v. 2.3.0
today I've updated to the version 2.3.1

![image001](https://github.com/PrestaShopCorp/ps_eventbus/assets/653230/c9016ba1-cd7d-4ad1-b7c9-29ad1afbf0d9)
![image002](https://github.com/PrestaShopCorp/ps_eventbus/assets/653230/5678419c-fb59-4e6c-b7b2-72a299085a76)

maybe it could help you

bye

**Comment by gouna15** [comment]
Hi,
same problem on prestashop 1.7.8.8

**Comment by naatdev** [comment]
Hello,
I'm experiencing the same issue on PrestaShop version 1.7.8.9 as well.

**Comment by albertorizzo** [comment]
Hello,
I'm experiencing the same issue, with the same errors.
Prestashop 1.7.8.5

**Comment by jokesterfr** [comment]
Thank you all for reporting the issue.
Can you confirm this issue happens at installation time?

`./src/Provider/ProductSupplierDataProvider.php` is indeed a file in the PS EventBus module. However upper mentioned screenshots does not help me much debugging the issue.

This project will soon be fully tested with E2E suite, including PrestaShop 1.7.8.10 support.

**Comment by maofree** [comment]
Hi @jokesterfr 
I haven't had this problem lately, I now use version v2.3.4
the problem occurred when updating the already existing version

**Comment by fox-john** [comment]
@maofree This issue has not been answered for a very long time. Since then, several versions of Ps_Eventbus have been released. We invite you to update your module and see if the problem persists.

If this is the case, we invite you to contact us again, either here or via support directly.

In the meantime, I am closing the ticket for prolonged inactivity.
